### ISSUE TITLE
Package mars_raw_utils_0.5.2_amd64.deb shows errors during archive decompression

### ISSUE THREAD

**Issue by isenberg** [MarsRaw/mars-raw-utils#20]
I haven't used the rust-based raw utils before, so don't know if that's something new only specific to this package release: Maybe github has problems with storing large package files? Does the same work on your side? See the sha 256 checksum in the end. That's what I downloaded from github today.

$ dpkg-deb --contents mars_raw_utils_0.5.2_amd64.deb 
drwxr-xr-x 0/0               0 2022-07-28 15:54 usr/
drwxr-xr-x 0/0               0 2022-07-28 15:54 usr/share/
drwxr-xr-x 0/0               0 2022-07-28 15:54 usr/share/doc/
drwxr-xr-x 0/0               0 2022-07-28 15:54 usr/share/doc/mars_raw_utils/
-rw-r--r-- 0/0            1242 2022-07-28 15:54 usr/share/doc/mars_raw_utils/copyright
drwxr-xr-x 0/0               0 2022-07-28 15:54 usr/bin/
-rwxr-xr-x 0/0         7867928 2022-07-28 15:54 usr/bin/mru
-rw-r--r-- 0/0           22431 2022-07-28 15:54 usr/share/doc/mars_raw_utils/README
drwxr-xr-x 0/0               0 2022-07-28 15:54 usr/share/mars_raw_utils/
drwxr-xr-x 0/0               0 2022-07-28 15:54 usr/share/mars_raw_utils/data/
-rw-r--r-- 0/0          976296 2022-07-28 15:54 usr/share/mars_raw_utils/data/M20_HELI_RTE_FLAT_V3.png
-rw-r--r-- 0/0           10966 2022-07-28 15:54 usr/share/mars_raw_utils/data/M20_MCZ_LEFT_INPAINT_MASK_V1.png
-rw-r--r-- 0/0           10980 2022-07-28 15:54 usr/share/mars_raw_utils/data/M20_MCZ_RIGHT_INPAINT_MASK_V1.png
-rw-r--r-- 0/0         5222428 2022-07-28 15:54 usr/share/mars_raw_utils/data/M20_SCAM_FLAT_RGB_Sol77_V2.png
-rw-r--r-- 0/0          113471 2022-07-28 15:54 usr/share/mars_raw_utils/data/M20_SCAM_MASK_Sol1_V1.png
-rw-r--r-- 0/0          971567 2022-07-28 15:54 usr/share/mars_raw_utils/data/M20_WATSON_FLAT_V0.png
-rw-r--r-- 0/0           29839 2022-07-28 15:54 usr/share/mars_raw_utils/data/M20_WATSON_INPAINT_MASK_V1.png
-rw-r--r-- 0/0          219194 2022-07-28 15:54 usr/share/mars_raw_utils/data/MSL_CCAM_FLAT_Sol32_V1.png
-rw-r--r-- 0/0            8175 2022-07-28 15:54 usr/share/mars_raw_utils/data/MSL_CCAM_MASK_Sol3122_V2.png
-rw-r--r-- 0/0          554788 2022-07-28 15:54 usr/share/mars_raw_utils/data/MSL_FLB_FLAT_V1.png
-rw-r--r-- 0/0          554788 2022-07-28 15:54 usr/share/mars_raw_utils/data/MSL_FRB_FLAT_V1.png
-rw-r--r-- 0/0         1475510 2022-07-28 15:54 usr/share/mars_raw_utils/data/MSL_MAHLI_FLAT_Sol2904_V1.png
-rw-r--r-- 0/0           14440 2022-07-28 15:54 usr/share/mars_raw_utils/data/MSL_MAHLI_INPAINT_Sol2904_V1.png
-rw-r--r-- 0/0           26154 2022-07-28 15:54 usr/share/mars_raw_utils/data/MSL_MCAM_LEFT_INPAINT_Sol3082_V1.png
-rw-r--r-- 0/0           24730 2022-07-28 15:54 usr/share/mars_raw_utils/data/MSL_MCAM_RIGHT_INPAINT_Sol3101_V1.png
-rw-r--r-- 0/0         1919300 2022-07-28 15:54 usr/share/mars_raw_utils/data/MSL_NLB_FLAT_V1.png
dpkg-deb (subprocess): decompressing archive 'mars_raw_utils_0.5.2_amd64.deb' (size=13215708) member 'data.tar': lzma error: unexpected end of input
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
dpkg-deb: error: tar subprocess returned error exit status 2

$ sha256sum mars_raw_utils_0.5.2_amd64.deb 
dde4e547e5f2d34eca61e0324153ef509f727ef0cd805912667376ce73b8a817  mars_raw_utils_0.5.2_amd64.deb

**Comment by kmgill** [comment]
Ah, this bug again. Will investigate.

**Comment by kmgill** [comment]
Completed. deb installation is part of the build testing.
