### ISSUE TITLE
cropping of images should be optional and be reflected in metadata

### ISSUE THREAD

**Issue by sschmaus** [MarsRaw/mars-raw-utils#51]
MRU crops most images during calibration. This step can't be disabled and the crop is also not propagated to the metadata yet. 

I have some processes that require knowledge of the exact subframing of an image to be known to work correctly. Ideally I would like to apply the crop myself in a later step. 

I would really appreciate it if you can add a command toggle to the calibrate command to disable cropping completely.

**Comment by kmgill** [comment]
I will be adding the `-S` option to the `calibrate` subcommand to disable cropping. 

In calibration profiles, I will be adding `auto_subframing` (default: true)

**Comment by sschmaus** [comment]
that should do it, thanks a lot!

**Comment by kmgill** [comment]
Completed
