### ISSUE TITLE
mru calibrate on MacOS Sonoma

### ISSUE THREAD

**Issue by Steve-Albers** [MarsRaw/mars-raw-utils#62]
Hello Kevin - I installed mru on MacOS Sonoma. When I run 'mru calibrate' it isn't producing an output image for some reason. Perhaps I'm missing something? Here is an example command:

mru calibrate -R 1.168 -G .861 -B .890 -i NLF_1322_0784308110_801ECM_N0613516NCAM02322_07_195J01.png
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 0/1

Thanks,

Steve

**Comment by kmgill** [comment]
I tried the same command and it worked. If you haven't, run `mru update-cal-data` to make sure you have all the calibration files

**Comment by Steve-Albers** [comment]
Thanks Kevin for the advice as running "mru update-cal-data" worked!
